steps:
  # Step 1: Build JAR using Maven
  - name: maven:3.8.6-openjdk-17
    entrypoint: mvn
    args: ["clean", "package", "-DskipTests"]

  # Step 2: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "europe-west1-docker.pkg.dev/gauva-15d9a/cloud-run-source-deploy/gauva_backend/gauva-backend-git:latest", "."]

  # Step 3: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "europe-west1-docker.pkg.dev/gauva-15d9a/cloud-run-source-deploy/gauva_backend/gauva-backend-git:latest"]

images:
  - "europe-west1-docker.pkg.dev/gauva-15d9a/cloud-run-source-deploy/gauva_backend/gauva-backend-git:latest"
